// Cart
export const ADD_ITEM = "ADD_ITEM";
export const REMOVE_ITEM = "REMOVE_ITEM";
export const OPEN_CART = "OPEN_CART";
export const INCREASE_QUANTITY = "INCREASE_QUANTITY";
export const DECREASE_QUANTITY = "DECREASE_QUANTITY";
export const SELECT_SIZE = "SELECT_SIZE";
export const GET_CART_ITEMS = "GET_CART_ITEMS";
export const SELECT_COLOR_CODE = "SELECT_COLOR_CODE";

// Clothes
export const GET_CLOTHES = "GET_CLOTHES";
export const GET_CLOTHES_ITEM_BY_ID = "GET_CLOTHES_ITEM_BY_ID";
export const SELECT_CLOTHES_BY_SIZE = "SELECT_CLOTHES_BY_SIZE";

// Currency
export const GET_CURRENCY = "GET_CURRENCY";
export const SET_CURRENCY = "SET_CURRENCY";
export const SET_CURRENCY_SELECTED = "SET_CURRENCY_SELECTED";
export const UPDATE_PRICE_VALUES = "UPDATE_PRICE_VALUES";

// Categories
export const GET_CATEGORIES = "GET_CATEGORIES";
export const SET_CATEGORY = "SET_CATEGORY";
export const SET_CURRENT_SELECTED_CATEGORY = "SET_CURRENT_SELECTED_CATEGORY";

// Loading
export const SET_LOADING = "SET_LOADING";
