// Cart
export const ADD_ITEM = "ADD_ITEM";
export const REMOVE_ITEM = "REMOVE_ITEM";
export const OPEN_CART = "OPEN_CART";
export const INCREASE_QUANTITY = "INCREASE_QUANTITY";
export const DECREASE_QUANTITY = "DECREASE_QUANTITY";
export const GET_CART_ITEMS = "GET_CART_ITEMS";
export const SET_SELECTED_ATTRIBUTE = "SET_SELECTED_ATTRIBUTE";

// Currency
export const GET_CURRENCY = "GET_CURRENCY";
export const SET_CURRENCY = "SET_CURRENCY";
export const SET_CURRENCY_SELECTED = "SET_CURRENCY_SELECTED";

// Categories
export const GET_CATEGORIES = "GET_CATEGORIES";
export const SET_CURRENT_SELECTED_CATEGORY = "SET_CURRENT_SELECTED_CATEGORY";
